### PR TITLE
[wip] Complement api service endpoints

### PR DESCRIPTION
**Pull request by xamanu**

### CODE REVIEW

**Comment by PDesire** [comment]
Nice approach, I like it. I also have done a different approach, try looking @ it, maybe we can inspire eachother :) 

https://github.com/thepublictransport/public-transport-enabler-tpt

**Comment by schildbach** [comment]
Thanks for your contribution! From a quick glance at your code, everything looks clean and straight-forward. It seems to follow the original vision of the subproject.

However to be honest I personally lost interest in maintaining a web service. If the goal of this effort is to develop the service subproject into a fully-fledged "product", then I would suggest I move the subproject into its own repository and grant commit access to a maintainer (e.g. you).

**Comment by xamanu** [comment]
Sure, I'd be up for a separate repository. Thanks, @schildbach.

**Comment by schildbach** [comment]
@xamanu What do you think about Gitlab? I could offer `https://gitlab.com/oeffi/public-transport-service`.

**Comment by xamanu** [comment]
Sounds good to me! I have the same username over there.

**Comment by schildbach** [comment]
Ok cool! I've created the project and added you as a maintainer. Welcome onboard!

**Comment by schildbach** [comment]
Since public-transport-enabler is still not versioned to date, I've changed that dependency to `compile 'de.schildbach.pte:public-transport-enabler:unspecified'`, to be satisfied from the local Maven repo. An alternative would have been to use a git submodule (like Öffi does atm) or of course start versioning pte. For now, I picked the simplest route.

**Comment by PDesire** [comment]
We did already the same (mentioned above), just wanted to tell ya I'll be ready to help out if you need some

**Comment by xamanu** [comment]
Thanks, @schildbach for setting this up.

@PDesire, looks great, you've been doing and I'll appreciate to get your help as Merge Requests on the repo to improve the code.

Closing here, I'm going to reroll the code on the other repo.

**Pull request closed without merging**
