### PR TITLE
Replace the HSL provider with a Navitia based one

### LINKED ISSUE #166: api.reittiopas.fi will shut down
Just got this mail from HSL:

> Dear HSL data user,
>
> The old HSL Journey Planner (classic.reittiopas.fi) will be discontinued at the end of November, causing changes for API users, too. HSL will continue to develop open data and open APIs. We hope that the transition to the new APIs will not cause you any issues and you will still be able to utilize the APIs for your needs.
>
> The following changes will take place in the autumn:
>
> 1\.      GTFS zip file will be relocated on 31 August 2017. The obsolete address is http://api.reittiopas.fi/data/google_transit.zip
> The new address is https://api.digitransit.fi/routing-data/v2/hsl/HSL.zip
>
> 2\.      The old Classic Journey Planner will be discontinued by the end of November and at the same time the routing API (http://api.reittiopas.fi/hsl/prod) and other outdated APIs will be run down.
>
> \-        Instructions and addresses for the new APIs can be found here: https://www.hsl.fi/en/node/10460 , partly in English.
>
> \-        We recommend you to start using the new API as soon as possible to enable us to respond to any development needs in the operation of the API.
>
> In case you have any problems, please send us a message on Facebook, Gitter or Twitter
>
> \-        Facebook https://www.facebook.com/HSLdevcom/  
>
> \-        Gitter https://gitter.im/HSLdevcom
>
> \-        Twitter https://twitter.com/HSLdevcom
>
> 
>
> With kind regards,
>
>Antero Karppinen and the Journey Planner development team

@msjoberg

### PR DESCRIPTION
**Pull request by aperezdc**
HSL is replacing their API [with a new one](https://digitransit.fi/en/developers/). Fortunately, Navitia has the data as well, and it's possible to replace the easily replace the old provider with one based on AbstractNavitiaProvider to keep things working until a provider for the new HSL API is written.

Fixes #166

----

**Edit** (2018/07/25): Merge request [submitted to the staging repository as well](https://gitlab.com/opentransitmap/public-transport-enabler/merge_requests/2).

### CODE REVIEW

**Comment by grote** [comment]
Mentioning @msjoberg as he was the original author of the HslProvider.

**Comment by msjoberg** [comment]
Yes, I wrote the original HslProvider, and I've noticed it has stopped working recently. Unfortunately I won't have time to write a new one for the new HSL API, so this sounds like the best course of action.

Given that the current one doesn't work I see the risk in switching as pretty low :-) I can definitely help out with testing it.

**Comment by aperezdc** [comment]
Is there any easy way I can tell Gradle to build Transportr with the local changes I have in PTE? That would be very helpful for me to do some testing as well. I tried putting the `public-transport-enabler` directory inside the `Transportr` one, like this:

```
Transportr/
     +-- public-transport-enabler/
     +-- README.md
     +-- ...
```

And then adding an `include ':public-transport-enabler'` in the top-level `settings.gradle` of Transportr, but Gradle doesn't play ball. Any suggestions?

**Comment by aperezdc** [comment]
I already commented this in [in the PR for Transportr](https://github.com/grote/Transportr/pull/479#issuecomment-407916859): the GTFS data for HSL does *not* include route/line colors, so I will need to update this PR to define the styles for them in `HslProvider`. Currently routes for all mods of transport are always painted black.

**Comment by jvanbruegge** [comment]
I am not sure how the Navitia data sources work, but I stumbled across this when looking to implement public transport in Tampere for Transportr. As the Navitia source does only specify Finland as whole, and there is [data for Tampere](https://navitia.opendatasoft.com/explore/dataset/fi/table/?sort=type_file), does this mean this PR would also extend the capabilities to Tampere and the other cities in Navitia?

**Comment by aperezdc** [comment]
@jvanbruegge Yes, Tampere is covered by the Navitia source. In https://github.com/grote/Transportr/pull/511 the UI in Transportr has been changed to reflect that. I have pending to rename `HslProvider` to `FinlandProvider` in PTE as well (Transportr is using the staging repo of PTE, which already has this PR merged).

**Comment by grote** [comment]
This has now merge conflicts, because the old HslProvider was removed.

**Comment by forthommel** [comment]
I would be happy to help this PR getting merged anytime soon! Please let me know :-)

**Comment by schildbach** [comment]
Merged!

**Comment by schildbach** [comment]
I renamed the provider to `FinlandProvider` though.

**Pull request closed without merging**
