### PR TITLE
Add prague provider

### PR DESCRIPTION
**Pull request by filip-hejsek**

### CODE REVIEW

**Comment by schildbach** [comment]
Thanks for your contribution! I'm sorry for the delay.

Does the "cz" region include only Prague? Theoretically, it should be the entire Czech Republic?

**Comment by schildbach** [comment]
Apart from the above question, the PR looks very good to me.

**Comment by filip-hejsek** [comment]
Well, right now it's only Prague because data for other cities aren't available in gtfs, though in the future other cities might be added.

**Comment by schildbach** [comment]
Thanks. If you don't mind I'll will then rename your provider to CzechRepublicProvider (and the NetworkId constand accordingly). Because it's likely Navitia will add other Czech cities under the cz region as well.

**Comment by filip-hejsek** [comment]
Yeah, it's probably better to rename it to CzechRepublicProvider.

**Comment by schildbach** [comment]
Renamed & merged.

**Pull request closed without merging**
