### PR TITLE
Use https for several providers

### PR DESCRIPTION
**Pull request by full-duplex**
Some providers (MERSEY, MVV, NASA, NS, NVBW, SNCB and VRR) still use an insecure url while the tests still pass when using a secure url. This pull request changes them to use https instead.

### CODE REVIEW

**Comment by schildbach** [comment]
Did you test all these URLs?

**Comment by full-duplex** [comment]
Yes, these are all the providers that were still using an http url, had at least some passing tests and the same amount of passing live tests when switched over to https.

One exception is SNCB where one test failed with the secure url, but this is fixed in the second commit.

**Comment by schildbach** [comment]
Great to hear. Seems like the companies feel a real push towards HTTPS. I checked these providers only a couple of weeks ago.

I'll merge this at the next occasion. The URL encoding bug I can't reproduce and also the '|' sign doesn't need to be encoded.

**Comment by full-duplex** [comment]
Are you sure? This is the url that the test uses and I can reproduce it in mutliple browsers and curl, confirming it's a server side issue.

```
https://www.belgianrail.be/jp/sncb-nmbs-routeplanner/query.exe/nny?performLocating=2&tpl=stop2json&look_stopclass=65535&look_nv=get_stopweight|yes&look_x=3407118&look_y=50748017&look_maxno=200&look_maxdist=5000
```

In fact, any url that has a pipe in it fails combined with https:

```
$ curl "https://www.belgianrail.be/|" 
curl: (56) GnuTLS recv error (-54): Error in the pull function.

$ curl "https://www.belgianrail.be/%7C"
<!DOCTYPE html>
...
```

**Comment by schildbach** [comment]
Just to record the state, I merged your first commit a while ago. The second one I still need to re-review. If you could rebase this PR it would be great.

**Comment by full-duplex** [comment]
While rebasing the fix, I found out that the SNCBProvider is broken. It looks like they removed the API that it relies on. This PR can be closed and the SNCBProvider should probably be removed.

**Comment by schildbach** [comment]
I switched SncbProvider back to HTTP, that fixes the problem.

**Pull request closed without merging**
