### PR TITLE
Navitia: Add Poland provider

### PR DESCRIPTION
**Pull request by mimi89999**

### CODE REVIEW

**Comment by mimi89999** [comment]
I managed to make all the tests except `queryDeparturesEquivsTrue`, `nearbyStationsPoi` and `queryDeparturesStopArea`.

**Comment by schildbach** [comment]
Are you living in Poland or traveling through Poland on a regular basis?

Does this provider (and the data Navitia provides) offer an improvement over PlProvider?

**Comment by mimi89999** [comment]
I live in Warsaw.

Yes. It does offer a great improvement. The PlProvider has many issues.

**Comment by schildbach** [comment]
Should we then perhaps replace PlProvider entirely? Is there any value in keeping it? Did you compare on the countryside too?

**Comment by mimi89999** [comment]
Sorry. I thought about the PlZtmProvider. The PlProvider is for trains and the PlNavitiaProvider is for transport in the city.

**Comment by schildbach** [comment]
Ok, I understand. I just merged your PR! Thanks a lot!

**Pull request closed without merging**
