### PR TITLE
Added Hungary provider

### PR DESCRIPTION
**Pull request by urbalazs**
Hi @schildbach 
This PR added Hungary provider, included two cities: Budapest (capital city) and Miskolc.

### CODE REVIEW

**Comment by urbalazs** [comment]
Hello @schildbach 
Can you check my pull request? It was merged to https://gitlab.com/opentransitmap/public-transport-enabler/commit/621c95e04a0593bb50d013cdd8ed33e289758a6d
It would be great to merge also to the „official” repository.

**Comment by schildbach** [comment]
Thanks for your contribution! I'd like to ask if there is someone checking the quality of the data provided by Navitia? Ideally a local person who uses a Navitia-based app in Hungary on a regular basis.

**Comment by meskobalazs** [comment]
This is an old PR but the Navitia data are coming from official GTFS sources, so their quality is good.

**Comment by schildbach** [comment]
Thanks a lot for your contribution. Unfortunately, due to the current bad shape of Navitia support in public-transport enabler, time constraints on our side and due to the centralized nature of navitia.io I have decided to drop support for Navitia. Thus, I'm going to close this PR. Sorry for the inconvenience and thanks again.

**Pull request closed without merging**
