### PR TITLE
Add support for Italy through Navitia

### PR DESCRIPTION
**Pull request by aelkhour**
Navitia gathers all local providers in one "it" region.
Currently Rome and Palermo are supported, although Palermo doesn't seem to have produced GTFS data since November...
So in practice, only Rome is working now, and this appears in the JUnit tests.

@schildbach let me know if you are ok with this.

### CODE REVIEW

**Comment by schildbach** [comment]
Thanks! I *think* I merged all of the Navitia commits for now. Can you rebase the rest (Italy) on current master?

A little bit of nitpicking: if you fix bugs or complete work you started in the same PR, there is no point in keeping the history. For example "create abstract test class" and "finish abstract test class" can be squashed together (I did this already).

**Comment by aelkhour** [comment]
Thanks for merging and your feedback!

I agree with you with respect to squashing, I tend to forget doing it. I rebased the branch and squashed some of the remaining commits in the PR.

**Comment by aelkhour** [comment]
@schildbach Could you please provide a target date for the merge? I'd like to know in order to plan future developments.

**Comment by schildbach** [comment]
I'm sorry, I totally forgot about this PR. I just squashed and merged it.

As with all Navitia based providers, currently are quite some live tests failing, but we can tackle this in later commits.

**Comment by grote** [comment]
Can't this be closed?

**Comment by schildbach** [comment]
Yes, sorry, forgot.

**Comment by aelkhour** [comment]
Thanks @schildbach!

**Pull request closed without merging**
