### PR TITLE
VRR: Line shapes

### PR DESCRIPTION
**Pull request by karottenbaum**
I forgot to add shapes to the tram line styles, so that's what I did here.
Sorry for the extra PR.

### CODE REVIEW

**Comment by grote** [comment]
CI failed, probably need to import `Shape`.

**Comment by schildbach** [comment]
Can you squash your PR into 1 commit?

**Comment by karottenbaum** [comment]
I'll try my best to find out how.

**Comment by schildbach** [comment]
On your branch, `git rebase -i master`

Then you replace the `pick` by `squash` or `fix` for those commits you want to merge into the previous one.

After that, `git push -f` to force-push over your branch in the GitHub PR.

A (future) shortcut for the first step is `git commit --amend` to fix a previous commit directly.

**Comment by karottenbaum** [comment]
I can't seem to get rid of 28bee76. If you want, I can redo this.

**Comment by schildbach** [comment]
Yes, that commit is there because you merged master into your branch. Hint: Never use merge, always use rebase: `git rebase master`

You can drop the commit when doing an interactive rebase, but don't worry – I did this for you and picked up your commit. Thanks!

**Pull request closed without merging**
