### PR TITLE
Some simple fixes for the AbstractNavitiaProvider

### PR DESCRIPTION
**Pull request by grote**
See the individual commit messages for details on the fixes.

### CODE REVIEW

**Comment by grote** [comment]
@aelkhour since the NavitiaProvider comes from you (thanks a lot!), you might also want to have a look at this PR.

**Comment by grote** [comment]
I updated this PR. It drops the distance parameter from the queryUri if it is 0 and adds a test for this. While I was at it, I also fixed all other ParisProviderLive tests.

**Comment by schildbach** [comment]
I picked the old version of distance commit, because I think that fits better with the other providers.

There are some leftovers, can you rebase?

**Comment by grote** [comment]
I don't know how you arrived in that state, but I managed to rebase my commits and it seems that just the fixes for the ParisProvider live tests are missing.

Thanks for merging so quickly!

**Comment by schildbach** [comment]
I used cunning git-foo (-:

Merged, thanks.

**Pull request closed without merging**
