### PR TITLE
AbstractNavitiaProvider: Remove all providers based on Navitia.

### PR DESCRIPTION
**Pull request by schildbach**
I propose to remove all providers based on Navitia. They have been causing many runtime errors since years, without anyone working on them. If we don't find a responsible maintainer for the Navitia API (mainly AbstractNavitiaProvider), we I think we'd rather remove these classes.

### CODE REVIEW

**Comment by schildbach** [comment]
Pinging @aelkhour and @grote as you're listed as authors.

**Comment by grote** [comment]
Also pinging @ialokim and @prhod about the removal of Navitia from PTE.

**Comment by ialokim** [comment]
I think it's less the PTE's implementation of `AbstractNavitiaProvider` that leads to problems, but instead the data on the Navitia server which is not always up-to-date or gets some updates changing IDs or such. I think we can not do much on PTE's side on this, apart from perhaps implementing a slightly better error handling.

It would be really a shame if all those providers were removed from PTE. I would be okay maintaining them to the extend that is possible without having access to the data source (Navitia API) itself.

**Comment by aelkhour** [comment]
@schildbach I don't have the bandwidth to maintain this provider. Although I am the instigator of this and had a lot of fun adding it, I understand your decision if there are no maintainers.

**Comment by schildbach** [comment]
> The removal of all providers based on Navitia would be a big loss :( What specific errors/problems are encountered with Navitia? I would be happy to help working those out :)

Sorry for getting back to your question only now.

I tagged most of the open issues with the tag "navitia".

**Comment by schildbach** [comment]
There is one more problem with Navitia: their API limit for free accounts seems to be exceeded by Öffi now and then. Not sure how other apps like Transportr do, but for Öffi this is quite discouraging.

**Comment by schildbach** [comment]
Merged.

**Pull request closed without merging**
