### PR TITLE
Navitia added NA physical mode for skytrain (Subway in BC)

### PR DESCRIPTION
**Pull request by anjandev**

### CODE REVIEW

**Comment by anjandev** [comment]
fixes #224

**Comment by anjandev** [comment]
Torsten Grote <notifications@github.com> writes:

> @grote commented on this pull request.
>
> ----------------------------------------------------------------------------------------------------
>
> In enabler/src/de/schildbach/pte/AbstractNavitiaProvider.java:
>
>> @@ -621,6 +621,8 @@ private Line parseLine(final JSONObject jsonRoute) throws IOException {
>  
>          switch (physicalMode) {
>          case BUS:
> +        case NA:
> +            return Product.SUBWAY;
>
> Not sure it makes sense to add this for all Navitia providers. What does NA stand for? If it means "not available", it
> might not always be subway.
>
> Also, the Skytrain in Vancover is more SUBURBAN_TRAIN or TRAM than SUBWAY I'd argue.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.

Ya, I think NA stands for not applicable. I couldnt find anything on the
Navitia website about it. I can add it to only the BC provider rather
than all Navitia providers.

I thought the skytrain was also more SUBURBAN_TRAIN but I check the
wikipedia page on subway:

https://en.wikipedia.org/wiki/Rapid_transit

and it stated that the transport system might be called the subway even
though it's primarily over ground (search for "skytrain") on this page.

I can change to SUBURBAN_TRAIN as that makes more sense.

Let me know what I should change to get this fixed.

**Comment by anjandev** [comment]
It seems that australia also has a `NA` physical mode:

http://canaltp.github.io/navitia-playground/play.html?request=https%3A%2F%2Fapi.navitia.io%2Fv1%2Fcoverage%2Fau%2Fphysical_modes%2Fphysical_mode%253ANA%2F%3F&token=6eb3adff-51bf-4e77-bb4b-508c09e91778


I will send a seperate PR that makes this code specific to the British Columbia Provider.

**Comment by schildbach** [comment]
Is this still `NA` physical mode still an issue? @prhod wanted to work on getting rid of those in the original data.

**Comment by prhod** [comment]
As stated in [this comment](https://github.com/schildbach/public-transport-enabler/issues/234#issuecomment-578662019), there should be no more issues like that.

**Comment by schildbach** [comment]
Ok, so I'll close this.

**Pull request closed without merging**
