### PR TITLE
SydneyProvider: Correct colours and add new lines

### PR DESCRIPTION
**Pull request by yue-dongchen**
This pull request corrects line colours and adds two new lines.

- Line colours
  - Unifying all bus lines into the single official colour, as colours that were previously in [SydneyProvider.java](https://github.com/schildbach/public-transport-enabler/blob/master/src/de/schildbach/pte/SydneyProvider.java) seem to be taken from operator maps such as [this](https://transportnsw.info/document/4247/state-transit-north-shore-and-west-network-map.pdf), which have a plethora of colours only for aesthetical purposes
    alt text
  - Correcting line colours according to precise hex values from [Transport for NSW open data](https://opendata.transport.nsw.gov.au/resources)
- New lines
  - 'M' (Sydney Metro Northwest): subway
  - 'L3' (Sydney Light Rail): tram

### CODE REVIEW

**Comment by schildbach** [comment]
Thanks for your contribution! I merged your new lines, but with the bus colors I'm not so happy. Lines usually are color coded so people can recognize them not only by their number but also by color. At least that's how it is in Europe – are the colors really "unused" in Sydney?

**Comment by yue-dongchen** [comment]
Although colour schemes for bus lines are logically used in many European cities (e.g. in [Munich](https://www.mvv-muenchen.de/plaene-bahnhoefe/plaene/index.html): green for ExpressBus "X" lines, orange for Metro-Bus two-digit lines, blue for three-digit Stadt-Bus lines, and a few other colours for Nachtlinien), they are much less consistent in Sydney - even within the same organisation.

For example, in the following two different network maps from the same public operator (State Transit), pretty much every adjacent line is given a different colour, unlike the consistency in the example of Munich. Furthermore, the overlapping areas of the maps have different colour. This is despite the maps being from the same operator and drawn by the same company (_Cartography by TransitGraphics_ on both maps).

1. [Eastern Suburbs](https://transportnsw.info/document/3952/buses-around-eastern-suburbs.pdf)
2. [North Shore & West](https://transportnsw.info/document/4247/state-transit-north-shore-and-west-network-map.pdf)

Therefore, they are more like theming for individual maps, without pertaining to much systematic sense. TfNSW's own [Trip Planner](https://transportnsw.info/trip#/trip) simply treats all bus lines as blue.

If you're satisfied with this explanation, I'll close this pull request.

**Comment by schildbach** [comment]
@yue-dongchen Are you a Sydney local? Or more like Munich/Germany based?

**Comment by yue-dongchen** [comment]
@schildbach I'm based in Sydney. That was just an example, since you'd mentioned colour schemes in Europe.

**Comment by schildbach** [comment]
Ok, then I'll trust you on the color coding conventions.

**Comment by schildbach** [comment]
Could you perhaps also check about the shapes used by the official signets? The bus signet you posted would be `Shape.CIRLE` (you'd need to use another `Style`constructor that accepts a shape). And it has a white border (yours is currently without border).

Can you rebase your PR on current master?

**Comment by yue-dongchen** [comment]
That's a good point. The circle signet is not tied to the line shapes (all [transport modes](https://transportnsw.info/plan/help-with-planning/key-to-icons-line-codes) have a circle icon), which are of the generic rounded style. It would be a nice feature for Transport for NSW to implement such distinctions, but there currently aren't any.

**E.g. buses and trains**
alt text
**Round ferry signet with generic rounded line shields**

grafik

**Comment by yue-dongchen** [comment]
It would be great if you could merge my colour commit, as no additional styling is required (explained in comment above).

Thanks a lot.

**Comment by yue-dongchen** [comment]
My bad, the line colours shouldn't be removed. I'll close this now.

**Pull request closed without merging**
