### PR TITLE
Properly create Locations with name and place in Navitia providers

### PR DESCRIPTION
**Pull request by grote**
Allow option to fix case of location names and simplify location parsing
code.

### CODE REVIEW

**Comment by grote** [comment]
I added another related commit that includes `POI`s in the `suggestLocations` result.

You better merge these PRs or I keep adding stuff ;)

**Comment by grote** [comment]
Are there any issues that block merging this PR?

**Comment by schildbach** [comment]
No worries, I just took a little break (-:

I merged your first commit. About the second commit, I wonder if those additional suggestions will work with trip queries. Are there already unit tests for such trip queries?

In future I think it'd be better to separate such commits into two PRs; I see to connection between them.

**Comment by grote** [comment]
>No worries, I just took a little break (-:

Good to have you back! :)

>I merged your first commit.

Thanks!

> About the second commit, I wonder if those
>additional suggestions will work with trip queries. Are there already
>unit tests for such trip queries?

No, I can make them. Will you if they are there?

>In future I think it'd be better to separate such commits into two PRs;
>I see to connection between them.

Will do.

**Comment by schildbach** [comment]
Yes, I'm fine with the change. I wonder if we should add an `EnumSet<LocationType> types` parameter to `suggestLocations()`, similar to `queryNearbyLocations()`.

Clarification to my previous comment: I meant "live test"…

**Comment by grote** [comment]
I'd be fine adding a `EnumSet<LocationType> types` parameter to `suggestLocations()`. How will you handle that in the other providers?

For the administrative regions, should we introduce a new location type or use either `ADDRESS` or `POI`. Currently, I think I am using `POI`.

**Comment by grote** [comment]
So I added a live test. Is it sufficient?

**Comment by schildbach** [comment]
Yes, that looks good. Thanks, merged.

**Comment by grote** [comment]
Wohoo! Thank you! :)

**Pull request closed without merging**
