### PR TITLE
Add missing regional (TER) and long-distance (Intercités) trains support

### PR DESCRIPTION
**Pull request by kalon33**
This commit should fix missing regional and long-distance trains support around Paris and in South-West of France.

### CODE REVIEW

**Comment by schildbach** [comment]
Merged, thanks!

**Comment by schildbach** [comment]
Sorry, un-merged. It doesn't compile.

**Comment by grote** [comment]
If I had to guess, I'd say that
```java
return new super.getLineStyle;
```
is not proper Java. You would need to do something like:
```java
return getLineStyle(product, code, color);
```

**Comment by kalon33** [comment]
Sorry, I'm only starting with Java and pretty tired today... I followed your advice, should be good now.

**Comment by kalon33** [comment]
@grote @schildbach Any updates on this? My last commit should fix the previous one.

**Comment by kalon33** [comment]
@schildbach is this now possible to merge this?

**Comment by schildbach** [comment]
Can you squash your two commits into one? The second is just a bugfix to the first, so we don't need them on master separately.

**Comment by kalon33** [comment]
@schildbach done :)

**Comment by schildbach** [comment]
It still doesn't compile. Please test your code.

I plan to use Travis to make sure the code compiles, but due to [a bug in Travis](https://github.com/travis-ci/travis-ci/issues/5227) I couldn't activate the change already.

**Comment by kalon33** [comment]
`return getLineStyle(product, code, color);` probably contains an error, but as I'm only starting in Java and don't know whole public-transport-enabler code, I don't know how to correct it. An idea?

Thanks for your help.

**Comment by schildbach** [comment]
No, the enum name is wrong. But the real question is: Did you ever compile this code?

**Comment by grote** [comment]
@kalon33 you might want to get an IDE like AndroidStudio which can be helpful for beginners. Otherwise run `gradle build` from the command line after making code changes to see if they compile. You can run the tests with `gradle -Dtest.single=ParisProviderLive test` for example after commenting out the exclude at the end of `enabler/build.gradle`.

**Comment by kalon33** [comment]
The original problem should be fixed now, and it properly builds on my machine.

**Comment by schildbach** [comment]
Merged, thanks.

**Pull request closed without merging**
