### PR TITLE
Add support for Oregon provider

### PR DESCRIPTION
**Pull request by craftyguy**
I've been waiting about an hour for a confirmation for a free navitia account, so I am not able to create a test for this yet.. Maybe someone with an account already will step up in the meantime :)

### CODE REVIEW

**Comment by grote** [comment]
Hey @schildbach, just letting you know that this PR now has Live Tests as well.

**Comment by grote** [comment]
@craftyguy This PR now has a merge conflict.

**Comment by craftyguy** [comment]
@grote Thanks for the heads up, the merge conflict has been resolved!

**Comment by craftyguy** [comment]
Is there anything else I can do to help get this PR accepted? My friends and I would REALLY like to have an open source public transit app for our state :D

**Comment by grote** [comment]
@craftyguy I'm sorry it takes @schildbach so long to merge this one. Just noticed it has a conflict again that needs resolving.

**Comment by craftyguy** [comment]
@grote conflict resolved, I think!

**Comment by grote** [comment]
That was quick! :) You now have two merge commits in this PR. Better would be to rebase on master and then force push your branch.

**Comment by craftyguy** [comment]
Ah, I was afraid that might be a problem. I'm fairly new to this, could you point me to some info that describes what you are referring to in more detail? I considered squashing my commits but didn't know enough about it to feel comfortable since my commits are spaced far apart.

**Comment by grote** [comment]
There's many different ways to do this. My personal workflow usually looks similar to this:
```
git fetch origin
git rebase -i origin/master
```
Then your editor opens with the commit list and you can change and move stuff around. In your case, you should just see one commit and when you close/save your editor, your branch should be cleanly rebased on current master HEAD.

**Comment by craftyguy** [comment]
Thank you for the help, I've resolved it :)

**Comment by craftyguy** [comment]
@schildbach 

Any chance of getting this PR reviewed and accepted/merged? Having this location would be very useful for myself and my friends (not to mention others in this area)!

**Comment by schildbach** [comment]
Ok, I'll merge it. It generally helps if someone tries this first in a real app.

**Comment by schildbach** [comment]
Merged.

**Comment by craftyguy** [comment]
I tested it with Transportr a few months ago, if that helps..

**Pull request closed without merging**
